import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useDispatch } from 'react-redux';
import { setStep } from '../redux/formSlice';
import Link from 'next/link';

export default function Home() {
  const dispatch = useDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/step-1">
            <button onClick={()=>{dispatch(setStep(1));}}>
            Enter
            </button>
        </Link>
      </main>
    </div>
  )
}
